### ISSUE TITLE
Intro mentions AI?

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares.github.io#1]
```
An artificial Intelligence (AI) technology incorporates with Blockchain technology to produce a secure and reliable Beyond Bitcoin financial ecosystem
```
What AI do you mean? I wasn't aware AI is being used?

**Comment by ioBanker** [comment]
I don't mean machine learning; I'd mention AI so later we can address the Smart Assets Margin Call Mechanism / GS smart functions and liquidity pools exchange rate determination and pool assets automated issuance.

**Comment by grctest** [comment]
Cool, I'm not up to speed with these new features yet, makes sense then 👍
