### ISSUE TITLE
Request: Link to awesome-bitshares repo

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares.github.io#2]
Can we add a link to awesome-bitshares in the menu? https://github.com/bitshares/awesome-bitshares 

Thanks

**Comment by abitmore** [comment]
I'm not sure where to put the link on bitshares.github.io. At least the https://github.com/bitshares/awesome-bitshares link is pretty obvious on the https://github.com/bitshares page.

**Comment by grctest** [comment]
True, that GitHub page is linked to via a few small circle buttons I hadn't spotted, probably unnecessary then
